DEBUG: true
MULTIGPU: 0
APEX: -1
N_EPOCHS: 1000
BATCH_SIZE: 1
learning_rate: 0.001 # 0.0025 # 0.005 too much
LR_STEP_SIZE: 100
network:
 use_classifier: false
optimizer: 'Adam'
weight_decay: 0.0001
HARD_MINING_FREQ: 1

