DEBUG: true
MULTIGPU: 0
APEX: -1
num_epochs: 1000
batch_size: 1
learning_rate: 0.001 # 0.0025 # 0.005 too much
lr_step_size: 100
network:
 use_classifier: false
optimizer: 'Adam'
weight_decay: 0.0001
HARD_MINING_FREQ: 1

