# DCIS segmentationm with classifier and folds. Depth 5 compared to other model 4 with 4. Rest same.
DEBUG: true
MULTIGPU: 0
APEX: -1
num_epochs: 600
batch_size: 1
learning_rate: 0.00025
lr_step_size: 150
network:
 use_classifier: true
 classifier_gradient_multiplier: 0.15
 num_base_filters: 64
 depth: 5
 dropout_probability: 0.1
optimizer: 'Adam'
weight_decay: 0.0001
HARD_MINING_FREQ: 1

