# DCIS classification. Same as exp0, but more filters (64->80) and depth 4 (5->4)
DEBUG: true
MULTIGPU: 0
APEX: -1
num_epochs: 600
batch_size: 1
learning_rate: 0.00025
lr_step_size: 150
network:
 use_classifier: true
 classifier_gradient_multiplier: 0.15
 num_base_filters: 80
 depth: 4
 dropout_probability: 0.1
optimizer: 'Adam'
weight_decay: 0.0001
HARD_MINING_FREQ: 1

